Repository llamara-ai/llamara-frontend, pull requests merged in 2025-03, with the labels that each got.

#10 Migrate from react-router-dom to react-router
  package-lock.json
  package.json
  src/PrivateRoute.tsx
  src/Routes.tsx
  src/services/GetSessionsService.tsx
  src/tests/services/GetSessionsService.test.tsx
  src/views/chatbot/Chatbot.tsx
  src/views/overlays/Overlay.tsx
  src/views/overlays/sidebar/SidebarContent.tsx
  src/views/overlays/sidebar/SidebarMainNav.tsx
  src/views/overlays/sidebar/SidebarUser.tsx
  src/views/security/LoginView.tsx
Labels: dependencies, javascript

#11 Fix navigation through sessions and subpages
  src/hooks/useChatMessages.ts
  src/lib/navigateToSession.ts
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/services/GetSessionsService.tsx
  src/views/chatbot/Chatbot.tsx
  src/views/overlays/Overlay.tsx
  src/views/overlays/sidebar/SidebarContent.tsx
  src/views/overlays/sidebar/SidebarMainNav.tsx
Labels: bug

#12 PDF Toolbar: Don't collapse in case no breakpoint is set
  src/components/pdf-toolbar.tsx
Labels: bug

#14 Knowledge Details: Show user any translation instead of * in permissions
  src/views/knowledge/KnowledgeOptions.tsx
  src/views/knowledge/KnowledgePermissions.tsx
  src/views/knowledge/TableExpandable.tsx
  src/views/knowledge/dialog/PermissionDialog.tsx
Labels: enhancement

#13 Knowledge Status: Fix width of badge to auto adjust to content
  src/views/knowledge/KnowledgeStatus.tsx
Labels: bug

#16 KnowledgeSourceDetail: Show user any translation instead of * in permissions
  src/views/chatbot/KnowledgeSourceDetail.tsx
Labels: enhancement

#19 Knowledge Actions: Reorder retry action & Enhance translations
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/views/knowledge/KnowledgeOptions.tsx
Labels: enhancement

#18 Knowledge Table: Display admin permission & Enable actions for admin
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/services/UserContextService.tsx
  src/views/knowledge/KnowledgeOptions.tsx
  src/views/knowledge/KnowledgePermissions.tsx
  src/views/overlays/sidebar/SidebarUser.tsx
Labels: bug

#24 Make knowledge source details card usable on touch devices
  src/hooks/useIsTouch.ts
  src/views/chatbot/KnowledgeSource.tsx
  src/views/chatbot/KnowledgeSourceDetail.tsx
Labels: enhancement

#27 Update knwoledge table tag and fix sorting of columns
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/views/knowledge/Columns.tsx
Labels: enhancement

#25 PDF Viewer: Highlight search query
  src/components/pdf-viewer.tsx
Labels: enhancement

#23 ChatMessage: Accept invalid JSON source references and process them properly
  src/views/chatbot/ChatMessage.tsx
Labels: enhancement

#28 Move action button next to search bar and fix overflow of knowledge page
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/views/knowledge/DataTable.tsx
  src/views/knowledge/Knowledge.tsx
  src/views/knowledge/KnowledgeOptions.tsx
  src/views/knowledge/dialog/UploadFileDialog.tsx
  src/views/overlays/Overlay.tsx
Labels: bug, enhancement

#29 Implement jump to & highlight source when opening PDF
  docs/openapi.json
  src/api/types.gen.ts
  src/components/pdf-viewer.tsx
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/views/chatbot/Chat.tsx
  src/views/chatbot/ChatMessage.tsx
  src/views/chatbot/Chatbot.tsx
  src/views/chatbot/KnowledgeSource.tsx
  src/views/chatbot/KnowledgeSourceDetail.tsx
Labels: enhancement

#30 Move LLMs can make mistakes hint into Chat component
  src/views/chatbot/Chat.tsx
  src/views/overlays/Footer.tsx
Labels: enhancement

#32 Chatbot: Fix PDF viewer behind close button & too high
  src/views/chatbot/Chatbot.tsx
Labels: bug

#34 Center knowledge table & Align PDF viewer with close button, unify distance to screen border
  src/views/chatbot/Chatbot.tsx
  src/views/knowledge/Knowledge.tsx
Labels: enhancement

#35 Sidebar: Fix safe-areas insets not respected
  index.html
  src/views/overlays/sidebar/Sidebar.tsx
  src/views/overlays/sidebar/SidebarContent.tsx
  src/views/overlays/sidebar/SidebarHeader.tsx
  src/views/overlays/sidebar/SidebarUser.tsx
Labels: bug

#37 Sidebar: Fix edit submit and adjust animation speed
  src/views/overlays/sidebar/SidebarSession.tsx
Labels: bug

#38 Make KnowledgeSourceDetail usable on (mobile) devices with small screens
  src/hooks/useMobile.ts
  src/views/chatbot/KnowledgeSource.tsx
  src/views/chatbot/KnowledgeSourceDetail.tsx
Labels: enhancement

#39 `useIsMobile`: Take the smaller edge into account instead of both edges
  src/hooks/useMobile.ts
Labels: enhancement

#40 PWA assets: Update generator config & Reduce padding for Apple touch icon
  index.html
  package.json
  public/apple-touch-icon-180x180.png
  public/favicon.ico
  pwa-assets.config.ts
Labels: enhancement

#41 CI Build: Update NodeJS version to match .nvmrc
  .github/workflows/build.yaml
Labels: infrastructure

#42 Fix left and right safe areas not respected by page content
  src/views/overlays/Footer.tsx
  src/views/overlays/Header.tsx
  src/views/overlays/Overlay.tsx
Labels: bug

#43 Empty chat banner: Improve positioning/style & Personalize title
  src/locales/de/translation.json
  src/locales/en/translation.json
  src/views/chatbot/Chat.tsx
Labels: enhancement

#44 Chat: Only focus on text input if not on touch device
  src/views/chatbot/Chat.tsx
Labels: bug

#51 Prevent scroll when virtual keyboard is opened
  src/main.tsx
Labels: bug

#52 Remove unused keycloak-js dependency
  package-lock.json
  package.json
Labels: dependencies, javascript
